package orchestrate

// searxng.go holds the v1.5 WEB-SEARCH (SearXNG) managed-service constants, view
// builders, and the net-new settings.yml render. Like
// memory.go (villa-qdrant/villa-embed) and openwebui.go, villa-searxng is NOT an
// inference Backend: it is a fixed OSS / digest-pinned managed service, so its image,
// settings mount, and secret-env-file contract are orchestrate-level managed-service
// constants — a DIFFERENT category from the GPU/Vulkan backend literals that
// internal/inference's TestSeamGrepGate guards (same category as openWebUIImage /
// qdrantImage). Living here keeps the inference seam gate green while giving Render()
// a dedicated, parseContainerArgs-free render path (no GPU device passthrough /
// supplemental-group args). The ghcr.io/searxng image literal below DOES trip the
// "container image literal" regex, so the seam_test.go isSeam allowlist is extended
// for orchestrate/searxng.go in the SAME commit (Pitfall 5), mirroring the
// orchestrate/memory.go precedent.
//
// The genuinely new sub-pattern this file invents (no prior managed service has it):
// rendering a mounted settings.yml CONFIG FILE from config. (the bounded
// engine allowlist) is realized as the rendered use_default_settings.engines.keep_only
// subset — the single-source vetted slice below is the auditable outbound surface.
//
// Secret discipline: the SearXNG secret_key NEVER reaches a 0644 file. It is
// generated by config.GenerateSearxngSecret (crypto/rand), persisted at 0600 in
// config.toml, and reaches the container via a Quadlet EnvironmentFile=<0600 path>
// directive — a separate searxng.env file (SEARXNG_SECRET=<value>) Plan 02 writes at
// 0600. The .container unit (written 0644 by WriteUnits) references that file by PATH
// only (SearXNGSecretEnvFilePath); the render path does not read the secret at all. The
// settings.yml renders secret_key empty (the live value arrives via the env var).

// searxngImage is the digest-pinned SearXNG metasearch image from the OFFICIAL
// ghcr.io/searxng org. SearXNG publishes ROLLING DAILY tags (not semver), so the tag
// is NOT pinnable — only the manifest-list digest is. This digest was ON-HARDWARE
// resolved on the live gfx1151 dev box during Plan 29-01 via `podman pull
// ghcr.io/searxng/searxng:latest` + `podman image inspect --format
// '{{index .RepoDigests 0}}'` (the same procedure Plan 19-03 used for qdrantImage),
// and a real format=json query confirmed the running container. The manifest-list
// digest is what ghcr serves; podman resolves the correct linux/amd64 variant
// (sha256:f63ce776…) from it automatically — mirroring qdrantImage, which also pins
// the RepoDigests[0] manifest-list digest, not a per-arch digest.
const searxngImage = "ghcr.io/searxng/searxng@sha256:ed29454ec1f7149986d42819b8b75265e545e79dd9187ba241c09f16a0fe56d0"

// SearXNGImage returns the digest-pinned SearXNG image so callers (e.g. the Phase-34
// backup manifest) record it WITHOUT re-typing the literal. The literal stays behind the
// orchestrate managed-service seam, mirroring QdrantImage()/OpenWebUIImage().
func SearXNGImage() string { return searxngImage }

// SearXNG stable Quadlet identity (this project's unit-name contract, asserted by the
// golden — it leaks no GPU/image assumption). The CONTAINER-DNS name is NOT a const
// here: it is config-resolved (config.SearxngAddr) and threaded into buildSearxngView
// so config is the single source of truth for the service's network identity.
const searxngContainerUnitName = "villa-searxng.container"

// SearXNGContainerUnitName returns the searxng .container unit filename Render appends
// when web search is enabled. EXPORTED so Plan 03's install flow can assert the unit is
// actually present in the written plan BEFORE starting its service (mirroring
// QdrantContainerUnitName) — gating the start on the rendered unit, not solely the config
// flag, so a web-search-on install whose unit is absent fails closed with a clear message.
func SearXNGContainerUnitName() string { return searxngContainerUnitName }

// searxngSecretEnvFileName is the BARE filename of the 0600 env file that carries the
// SEARXNG_SECRET. It is the single source the .container unit (via EnvironmentFile=) and
// Plan 02's writer (WriteSearxngSecretEnv) share — neither end re-types the literal.
const searxngSecretEnvFileName = "searxng.env"

// searxngSettingsMount is the read-only villa-owned config-DIRECTORY bind with the :Z
// PRIVATE SELinux label (mirrors memory.go's :Z discipline). SearXNG reads
// /etc/searxng/settings.yml; villa renders settings.yml (and the secret env file) into
// %h/.config/villa/searxng and mounts the whole dir read-only (a DIRECTORY bind, not a
// single-file bind — single-file binds interact badly with SELinux relabel + atomic
// rename writes, RESEARCH Open Q3). %h is Quadlet's home-dir specifier, resolved at
// unit-load time.
const searxngSettingsMount = "%h/.config/villa/searxng:/etc/searxng:ro,Z"

// searxngSecretEnvFilePath is the container-side EnvironmentFile= path the unit
// references and Plan 02's writer targets at 0600. %h is Quadlet's home-dir specifier
// (resolved at unit-load), so the env file lives in the SAME villa searxng config dir as
// settings.yml. The .container unit references this path ONLY — the secret VALUE never
// lands in the unit.
const searxngSecretEnvFilePath = "%h/.config/villa/searxng/" + searxngSecretEnvFileName

// SearXNGSecretEnvFilePath returns the EnvironmentFile= path the searxng unit references
// (the host side of the same dir as settings.yml). EXPORTED as the cross-plan secret
// contract: Plan 02 writes the searxng.env file at THIS exact path at mode 0600; the unit
// references it by path only. The secret value never appears in any 0644 file.
func SearXNGSecretEnvFilePath() string { return searxngSecretEnvFilePath }

// searxngEngines is the SINGLE-SOURCE vetted engine subset (RESEARCH A1): the
// bounded use_default_settings.engines.keep_only allowlist. ≤4 high-trust general/
// reference engines (duckduckgo/brave/wikipedia/wikidata) — excludes Google/Bing direct
// (rate-limit/CAPTCHA self-hosted), social/forum engines (injection surface), and image/
// video engines (out of scope for v1.5 text grounding). This slice IS the auditable
// outbound surface Phase 33's `villa verify search` cross-checks; an operator change is a
// one-line edit + golden re-freeze. Order is fixed so the rendered settings.yml golden is
// deterministic.
var searxngEngines = []string{
	"duckduckgo",
	"brave",
	"wikipedia",
	"wikidata",
}

// searxngView is the data searxng.container.tmpl renders: container-DNS only on
// villa.network, NO published host port. SecretEnvFile is the EnvironmentFile= PATH
// (not the secret value — render no longer reads the secret); SettingsMount is the
// read-only /etc/searxng:ro,Z dir bind.
type searxngView struct {
	ContainerName string
	Image         string
	Network       string
	SecretEnvFile string
	SettingsMount string
}

// settingsYmlView is the data searxng-settings.yml.tmpl renders: the bounded engine
// keep_only subset. server.secret_key renders EMPTY (the live value arrives via
// $SEARXNG_SECRET from the EnvironmentFile, never written into this 0644-capable file
// Pitfall 2); limiter/image_proxy/formats are fixed render-time decisions.
type settingsYmlView struct {
	Engines []string
}

// buildSearxngView assembles the SearXNG container view. ContainerName is the
// config-resolved container-DNS name (searxngAddr, threaded from in.Cfg — the single
// source of truth) so the rendered unit's identity derives from config, NEVER an
// orchestrate-local const. The image, the EnvironmentFile path, and the :Z settings mount
// stay genuine pinned managed-service constants (no config field for them; the secret
// VALUE is deliberately NOT threaded into the view — the render never reads it).
func buildSearxngView(searxngAddr string) searxngView {
	return searxngView{
		ContainerName: searxngAddr,
		Image:         searxngImage,
		Network:       networkAttach,
		SecretEnvFile: searxngSecretEnvFilePath,
		SettingsMount: searxngSettingsMount,
	}
}

// buildSettingsYml assembles the settings.yml view from the vetted engine subset. The
// engines slice is the single-source allowlist (searxngEngines) threaded as a
// parameter so the render and any future audit bind one symbol.
func buildSettingsYml(engines []string) settingsYmlView {
	return settingsYmlView{Engines: engines}
}

// SearxngEngines returns a copy of the single-source vetted engine subset so
// callers (the Phase-33 outbound audit) read the allowlist WITHOUT re-typing it. A copy
// is returned so callers cannot mutate the package-level slice.
func SearxngEngines() []string {
	out := make([]string, len(searxngEngines))
	copy(out, searxngEngines)
	return out
}

// searxngSecretEnvBody renders the 0600 env-file body Plan 02 writes and the unit
// references via EnvironmentFile=. It is a fixed `SEARXNG_SECRET=<value>` line (no shell
// interpolation; the value is a hex secret from crypto/rand). Single source of the env-
// file FORMAT — Plan 02's writer emits exactly these bytes at 0600.
func searxngSecretEnvBody(secret string) string {
	return "SEARXNG_SECRET=" + secret + "\n"
}

// searxngSecretEnvName returns the bare env-file filename (single source shared with
// Plan 02's writer).
func searxngSecretEnvName() string { return searxngSecretEnvFileName }
