package orchestrate

// websafe.go holds the v1.5 GROUNDED-FETCH (villa-websafe) managed-service constants
// and view builder (Phase-31 GUARD-01/GROUND-01). Like searxng.go / memory.go /
// openwebui.go, villa-websafe is NOT an inference Backend: it is a fixed, digest-pinned
// managed service, so its base image, secret-env-file contract, and binary bind-mount are
// orchestrate-level managed-service constants — a DIFFERENT category from the GPU/Vulkan
// backend literals that internal/inference's TestSeamGrepGate guards (same category as
// openWebUIImage / qdrantImage / searxngImage). Living here keeps the inference seam gate
// green while giving Render() a dedicated, parseContainerArgs-free render path (no GPU
// device passthrough / supplemental-group args). The distroless image literal below DOES
// trip the "container image literal" regex, so the seam_test.go isSeam allowlist is
// extended for orchestrate/websafe.go in the SAME commit (Pitfall 5), mirroring the
// orchestrate/searxng.go + orchestrate/memory.go precedent.
//
// The genuinely new sub-pattern this file invents (no prior managed service has it):
// BIND-MOUNTING THE HOST villa BINARY read-only into a minimal base and exec-ing the
// hidden `villa websafe-serve` subcommand (Area 1). No new build/publish pipeline: the
// same single static binary runs a new subcommand in a container context. The host binary
// PATH is a config-threaded value (os.Executable() captured at install time), NEVER
// shell-interpolated and NEVER an orchestrate-local const (RESEARCH Pattern 1).
//
// Secret discipline (T-31-12): the EXTERNAL_WEB_LOADER_API_KEY bearer NEVER reaches a
// 0644 file. It is generated by config.GenerateWebLoaderSecret (crypto/rand), persisted at
// 0600 in config.toml, and reaches BOTH the villa-websafe container AND the OWUI container
// via a Quadlet EnvironmentFile=<0600 path> directive — a separate websafe.env file
// (EXTERNAL_WEB_LOADER_API_KEY=<value>) Plan 02's writer emits at 0600. The .container unit
// (written 0644 by WriteUnits) references that file by PATH only (WebsafeSecretEnvFilePath);
// the render path does not read the secret at all.

import (
	"strconv"
	"strings"
)

// websafeImage is the digest-pinned distroless base the bind-mounted villa binary runs in.
// gcr.io/distroless/static-debian12 is the OFFICIAL Google distroless artifact purpose-built
// to run a single static binary (no shell, no package manager, minimal attack surface; CA
// certs included for HTTPS fetches). The digest is ON-HARDWARE resolved on the gfx1151 dev
// box via `podman pull gcr.io/distroless/static-debian12:nonroot` + `podman image inspect
// --format '{{index .RepoDigests 0}}'` (the same procedure searxngImage/qdrantImage used).
//
// Resolved on the gfx1151 dev box (Plan 04 Task 1, 2026-06-19) after confirming the static
// binary: `file ./villa` (built CGO_ENABLED=0 via `make build-static`) reports "statically
// linked", and `villa detect` runs correctly CGO-free (detection reads /proc + /sys; no cgo
// needed on Linux — Pitfall 5 cleared, no alpine fallback required). The bind-mounted villa binary
// MUST therefore be the static build; web-search opt-in requires `make build-static`.
const websafeImage = "gcr.io/distroless/static-debian12@sha256:b669b9df05a88a085fefed6520c6d2268aabacf3008b149ddf877e752ae89400"

// WebsafeImage returns the digest-pinned distroless base image so callers (e.g. the
// Phase-34 backup manifest) record it WITHOUT re-typing the literal. The literal stays
// behind the orchestrate managed-service seam, mirroring SearXNGImage()/QdrantImage()/
// OpenWebUIImage().
func WebsafeImage() string { return websafeImage }

// villa-websafe stable Quadlet identity (this project's unit-name contract, asserted by the
// golden — it leaks no GPU/image assumption). The CONTAINER-DNS name is NOT a const here:
// it is config-resolved (cfg.WebsafeAddr) and threaded into buildWebsafeView (WR-01), so
// config is the single source of truth for the service's network identity.
const websafeContainerUnitName = "villa-websafe.container"

// WebsafeContainerUnitName returns the villa-websafe .container unit filename Render appends
// when web search is enabled. EXPORTED so the install flow can assert the unit is actually
// present in the written plan BEFORE starting its service (mirroring SearXNGContainerUnitName)
// — gating the start on the rendered unit, not solely the config flag, so a web-search-on
// install whose unit is absent fails closed with a clear message.
func WebsafeContainerUnitName() string { return websafeContainerUnitName }

// websafeSecretEnvFileName is the BARE filename of the 0600 env file that carries the
// EXTERNAL_WEB_LOADER_API_KEY bearer. It is the single source the .container unit (via
// EnvironmentFile=) and Plan 02's writer (RenderWebsafeSecretEnv) share — neither end
// re-types the literal.
const websafeSecretEnvFileName = "websafe.env"

// websafeSecretEnvFilePath is the container-side EnvironmentFile= path the unit references
// and Plan 02's writer targets at 0600. %h is Quadlet's home-dir specifier (resolved at
// unit-load), so the env file lives in the villa websafe config dir. The .container unit
// references this path ONLY — the secret VALUE never lands in the unit (T-31-12).
const websafeSecretEnvFilePath = "%h/.config/villa/websafe/" + websafeSecretEnvFileName

// WebsafeSecretEnvFilePath returns the EnvironmentFile= path BOTH the villa-websafe unit AND
// the OWUI unit reference. EXPORTED as the cross-plan secret contract: Plan 02 writes the
// websafe.env file at THIS exact path at mode 0600; both units reference it by path only. The
// secret value never appears in any 0644 file (T-31-12).
func WebsafeSecretEnvFilePath() string { return websafeSecretEnvFilePath }

// websafeView is the data websafe.container.tmpl renders: container-DNS only on
// villa.network, NO published host port (PRIV-01). SecretEnvFile is the EnvironmentFile=
// PATH (not the secret value — render no longer reads the secret); BinaryMount is the
// read-only host-binary bind (:ro,z SHARED label); Exec is the fixed-token websafe-serve
// invocation.
type websafeView struct {
	ContainerName string
	Image         string
	Network       string
	SecretEnvFile string
	BinaryMount   string
	Exec          string
}

// buildWebsafeView assembles the villa-websafe container view. ContainerName is the
// config-resolved container-DNS name (websafeAddr, threaded from in.Cfg — the single source
// of truth, WR-01) so the rendered unit's identity derives from config, NEVER an
// orchestrate-local const. BinaryMount binds the HOST villa binary (hostVillaPath, captured
// via os.Executable() at install time and threaded through RenderInput — NEVER
// shell-interpolated) read-only with the LOWERCASE :ro,z SHARED SELinux label (the
// memory.go embedModelMount precedent for a read-only shared bind, NOT the :Z private label
// durable data volumes use). The image, the EnvironmentFile path, and the :ro,z label stay
// genuine pinned managed-service constants (the secret VALUE is deliberately NOT threaded
// into the view — the render never reads it, T-31-12).
func buildWebsafeView(websafeAddr, hostVillaPath string, websafePort int) websafeView {
	return websafeView{
		ContainerName: websafeAddr,
		Image:         websafeImage,
		Network:       networkAttach,
		SecretEnvFile: websafeSecretEnvFilePath,
		BinaryMount:   hostVillaPath + ":/usr/local/bin/villa:ro,z",
		Exec:          buildWebsafeExec(websafePort),
	}
}

// buildWebsafeExec assembles the websafe-serve Exec from FIXED tokens joined on a single
// space (NO shell interpolation, mirrors memory.go buildEmbedExec, T-31-13/T-03-01). The
// bind-mounted binary lives at /usr/local/bin/villa; `websafe-serve` is the hidden internal
// subcommand. --host 0.0.0.0 is container-internal ONLY (no host bind, PRIV-01); --port is
// the config-resolved villa-websafe in-network port so the served port matches the
// EXTERNAL_WEB_LOADER_URL OWUI composes (WR-01).
func buildWebsafeExec(port int) string {
	tokens := []string{
		"/usr/local/bin/villa",
		"websafe-serve",
		"--host", "0.0.0.0", // container-internal only; no host bind (PRIV-01)
		"--port", strconv.Itoa(port),
	}
	return strings.Join(tokens, " ")
}

// websafeSecretEnvBody renders the 0600 env-file body Plan 02 writes and BOTH units
// reference via EnvironmentFile=. It is a fixed `EXTERNAL_WEB_LOADER_API_KEY=<value>` line
// (no shell interpolation; the value is a hex secret from crypto/rand). Single source of the
// env-file FORMAT — Plan 02's writer emits exactly these bytes at 0600.
func websafeSecretEnvBody(secret string) string {
	return "EXTERNAL_WEB_LOADER_API_KEY=" + secret + "\n"
}

// websafeSecretEnvName returns the bare env-file filename (single source shared with Plan
// 02's writer).
func websafeSecretEnvName() string { return websafeSecretEnvFileName }
