package config

import "testing"

// FuzzParse feeds arbitrary bytes to Parse, the entry point for a hand-edited
// config.toml (also used by `villa restore` to turn an archived config.toml
// back into a VillaConfig). Untrusted here means "not generated by SaveVilla",
// not "network-attacker-controlled" -- but a corrupted or manually mangled
// file is exactly the case Parse's own doc comment calls out ("a malformed
// payload is a real error"), so it must never panic on one. A successful
// parse must also survive re-marshaling, since every save-bearing command
// round-trips through marshalVilla.
func FuzzParse(f *testing.F) {
	valid, err := marshalVilla(defaultConfig())
	if err != nil {
		f.Fatalf("marshalVilla(defaultConfig()): %v", err)
	}
	f.Add(valid)
	f.Add([]byte(`model = "qwen3.6-35b-a3b"
quant = "UD-Q4_K_M"
ctx = 131072
backend = "rocm"
dashboard_port = 8888
chat_port = 3000
`))
	f.Add([]byte(`speculation = "not-a-real-mode"`))
	f.Add([]byte(`dashboard_port = "not-an-int"`))
	f.Add([]byte(`[[nested`))
	f.Add([]byte(`not toml at all {{{`))
	f.Add([]byte(``))
	f.Add([]byte("model = \"a\"\x00\xff"))

	f.Fuzz(func(t *testing.T, data []byte) {
		cfg, err := Parse(data)
		if err != nil {
			return
		}
		if _, mErr := marshalVilla(cfg); mErr != nil {
			t.Fatalf("marshalVilla(Parse(data)) failed on an accepted config: %v", mErr)
		}
	})
}
